
--01. USER Required to identify schema/tables

CREATE USER LDMSTest IDENTIFIED BY LDMSTest;

GRANT CREATE SESSION TO LDMSTest;
GRANT CREATE PROCEDURE TO LDMSTest;
GRANT CREATE TABLE TO LDMSTest;
GRANT RESOURCE TO LDMSTest;


/* --Rollback
DROP USER LDMSTest;

--*/