
--02. Create Departments Table - 3 columns (REQ 1)

CREATE TABLE TBL_Departments
    (
    Departments_ID NUMBER (5) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Departments_Name VARCHAR2 (50) NOT NULL,
    Departments_Location VARCHAR2 (50) NOT NULL,
    CONSTRAINT TBL_Departments_PK PRIMARY KEY (Departments_ID)
    );

--03. Create Employees Table - 7 columns (REQ 1)

CREATE TABLE TBL_Employees
    (
    Employees_ID NUMBER (10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Employees_Name VARCHAR2 (50) NOT NULL,
    Employees_Job_Title VARCHAR2 (50) NOT NULL,
    Employees_Manager_ID NUMBER (10) NULL,
    Employees_Date_Hired DATE NOT NULL,
    Employees_Salary NUMBER (10) NOT NULL,
    Employees_Department_ID NUMBER (5) NOT NULL,
    
    CONSTRAINT Employees_PK PRIMARY KEY (Employees_ID),
    CONSTRAINT Employees_Departments_FK FOREIGN KEY (Employees_Department_ID)
        REFERENCES LDMSTest.TBL_Departments(Departments_ID)
    );
  

      
--Rollback - DROP Statements for All of the above

/*

DROP TABLE LDMSTest.TBL_Employees;
DROP TABLE LDMSTest.TBL_Departments;

SELECT TABLE_NAME, OWNER FROM ALL_TABLES
WHERE OWNER = 'LDMSTEST'
ORDER BY 2 
*/